---
title: "Generating dynamic assessment questions with NUMBAS"
description: "Positives and negatives of NUMBAS questions for mathematical assessment"
author: "Tamsin Smith, Evi Papadaki"
date: 12/06/2024
draft: false
editor: source
categories:
    - NUMBAS
    - VLE
    - Assessment
    - Automatic feedback
---

<br>

The [Maths Resource Centre](https://www.bath.ac.uk/professional-services/mathematics-resources-centre-mash/) at the University of Bath has a long history of using and developing NUMBAS questions for mathematical assessments. [NUMBAS](https://www.numbas.org.uk/) is a free open-sourced web-based system designed for creating dynamic assessment questions.

There are several advantages to using NUMBAS, including immediate feedback for students, which helps them to learn and adjust their understanding in real-time. The randomization feature also allows students to practice questions repeatedly with different data sets, reinforcing their skills and enhancing their learning experience. However, there are some limitations. One of the main drawbacks is the lack of personalized feedback, which means students may not receive tailored advice on their progress. Additionally, the need to code specific contexts for the questions can limit the extent of randomization, potentially reducing the variety of practice scenarios.

The MAST service of the Maths Resource Centre, led by us, has expanded the use of NUMBAS questions by incorporating them as creative tools within the teaching process. One of the first innovations was to contextualize the mathematics for different disciplines. This initiative began in response to a request from a specific subject area where students needed to develop mathematical and data analysis skills to support their subject understanding and problem-solving. It was also a response to the diverse entry profiles of the student cohort.

Further developments include collaborations where NUMBAS has been used in summative assessments, featuring randomised data sets. Additionally, it has been embedded in lecture materials as a live teaching tool, enhancing the overall learning experience.

If you're interested in our work, [take a look at our poster presented at the INDRUM 2024 conference](INDRUM2024Poster.pdf), or explore some examples of the questions developed by the team below.

<br>

```{=html}
<iframe width="100%" height="1208" src="https://numbas.mathcentre.ac.uk/exam/37971/prime-blogpost-example-questions/embed/?token=47dfb0bb-30d3-4d98-b948-6d1afbb8ad6a" title="Exemplar Numbas Questions"></iframe>
```

<br>
